version: "3"

services:
  app:
    image: display
    environment:
      - DISPLAY=${DISPLAY} # it works only in ubuntu
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: gazebo
    privileged: true
